# Generated by Django 4.1.3 on 2022-11-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
