# Generated by Django 4.1.3 on 2022-11-22 17:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_lead_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('intro', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('tags', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='blog')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('categories', models.ManyToManyField(to='blog.category')),
            ],
        ),
    ]
